### ISSUE TITLE
Not all posts links are generated in some categories

### ISSUE THREAD

**Issue by clmbmb** [mkamarin/Hugo-2-Gopher-and-Gemini#1]
I know it's pretty generic, but here's an issue I found:

On my Hugo site I have a category named `Cronica de concert` - this is the most used category on my blog.

The issue:
When running `python3 themes/Hugo-2-Gopher-and-Gemini/src/hugo2gg.py --type gemini` the `categories/cronica-de-concert.gmi` is generated, but not all links are listed. It ends abruptly at the 37th link. Here's the page in case: `gemini://calmbomb.pollux.casa/categories/cronica-de-concert.gmi`.

I also tried running `hugo --config config-gg.toml --destination public-gg --layoutDir layouts-gg --disableKinds sitemap` and I can see that `categories/cronica-de-concert/gemini/gemini-page.gmi` is correct - all links are present and correctly generated, but running the python script with `--no-hugo` will generate the wrong `categories/cronica-de-concert.gmi`.

**Comment by mkamarin** [comment]
I suspect the issue may be in the generated `categories/cronica-de-concert/gemini/gemini-page.gmi` around the 37th link. It also seems like the 37th link was not  generated correctly either (it shows as /posts/2014-1013). So, it may be a character or character sequence in the label of that link that is somehow creating the issue.

I will be happy to fix the issue, for that I will need more information. I will appreciate if you can do the following few things:

1- Be sure that you are using the latest version, as I did some fixes  couple of weeks ago. I will like to reproduce the issue with that version.
2- It will be useful to see the Hugo generated `categories/cronica-de-concert/gemini/gemini-page.gmi` around the link 37th. Few lines before and few lines after. Let say from link 35th (Nov 18, 2014) to link 40th. So, that I can see what is different in link 37th and I can test it.
3- If during this process you find the issue yourself, let say that it was a character sequence that is  causing the problem. Please, let me know, so that I can fix it in the code.

Thanks.

**Comment by clmbmb** [comment]
1. I'm using the latest version. In fact this is the first time I'm using your theme and I cloned the repo two days ago.
2. Here's how the content of `categories/cronica-de-concert/gemini/gemini-page.gmi` looks like:
```
=> /gemini/posts/2015-03-14-bfp/gemini-page.gmi March 14, 2015 BFP                                                                                                                                                  
=> /gemini/posts/2014-11-18-fabrica-hardcore/gemini-page.gmi November 18, 2014 Fabrica Hardcore                                                                                                                     
=> /gemini/posts/2014-11-03-talbot-tragic-question-mark/gemini-page.gmi November 3, 2014 Talbot, Tragic @ Question Mark                                                                                             
=> /gemini/posts/2014-10-13-entombed-in-a-grave/gemini-page.gmi October 13, 2014 Entombed in a Grave                                                                                                                
=> /gemini/posts/2014-10-12-9-7-grade-la-ground-zero/gemini-page.gmi October 12, 2014 9.7 grade la Ground Zero                                                                                                      
=> /gemini/posts/2014-07-09-come-back-kids/gemini-page.gmi July 9, 2014 Come back, kids!
```
I really don't see anything special about this link and I can't think of what the problem is.

If you have any idea that I can test, please let me know. Also, if you want to test, you can clone my public repo (where the posts are: https://codeberg.org/clmbmb/calmbomb

**Comment by mkamarin** [comment]
Thanks for the info. I was unable to clone your repository (even after creating an account in Codeberg), but I was able to reproduce the problem by generating a test suit with a large set of posts (a 1000 posts). 
It turns out that python's readline() is only returning the first 4096 characters of the input file. So, it is probably related to a buffer or something similar. I need to figure out how to read beyond that.
I plan to work on that this week, and should have a fix in few days.

**Comment by clmbmb** [comment]
Thanks for looking into it. I'll monitor the changes and will try again when you push them.

**Comment by mkamarin** [comment]
The issue has been fix. Please try it...
